export const LOCALSTORAGE_KEY_DISCARDED_DB = 'PPTIST_DISCARDED_DB'
export const LOCALSTORAGE_KEY_LIGHT_CACHE = 'PPTIST_LIGHT_CACHE'
export const LOCALSTORAGE_KEY_APP_CLIPBOARD = 'PPTIST_APP_CLIPBOARD'